"""Audit the unsupported fixed-depth terminal-value margin.

The scheduled certificate used in the manuscript compares

    G_{j,L}(z) -> G_{j+1,L-1}(F_k z),

so the Bellman margin is `[Phi(z)-tau]_+`.  A stronger fixed-depth value
theorem would require a positive margin for

    G_{j,L}(z) -> G_{j+1,L}(F_k z)

outside the residual set.  This script audits that stricter condition on the
shifted-tail terminal states generated by the current two-level controllers.
The default stride is deliberately coarse because fixed-depth evaluation is
much more expensive than the scheduled Bellman identity.
"""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass

import numpy as np

from horizon_lyapunov import (
    candidate_controls,
    default_beam_width,
    interaction_frame_operator,
    problem,
    random_disorder,
    step_precomputed,
)
from paths import result_path
from shifted_fallback_horizon import rollout_sequence
from shifted_fallback_margin_audit import (
    MarginConfig,
    select_with_margin_record,
    terminal_phi,
)
from terminal_value_certificate_audit import terminal_value
from terminal_value_shifted_horizon import (
    TerminalValueHorizonConfig,
    select_terminal_value_sequence,
)


@dataclass(frozen=True)
class FixedDepthAuditConfig:
    value_depths: tuple[int, ...] = (1,)
    audit_stride: int = 10
    terminal_weight: float = 1.0
    control_stage_weight: float = 0.0


def fixed_depth_margin(
    p,
    terminal_states: tuple[np.ndarray, ...],
    strengths: tuple[float, ...],
    controls_cache: tuple[tuple[np.ndarray, ...], ...],
    disorder_cache: tuple[tuple[np.ndarray, ...], ...],
    start_index: int,
    dt: float,
    candidates: tuple[np.ndarray, ...],
    depth: int,
    worst_weight: float,
    residual_threshold: float,
    terminal_weight: float,
    control_stage_weight: float,
) -> dict[str, float | int]:
    phi_now = terminal_phi(p, terminal_states, worst_weight)
    current_value = terminal_value(
        p,
        terminal_states,
        strengths,
        controls_cache,
        disorder_cache,
        start_index,
        dt,
        candidates,
        depth,
        worst_weight,
        residual_threshold,
        terminal_weight,
        control_stage_weight,
    )
    cache_index = min(start_index, len(controls_cache) - 1)
    records = []
    for candidate_index, candidate in enumerate(candidates):
        next_states = step_precomputed(
            terminal_states,
            strengths,
            controls_cache[cache_index],
            disorder_cache[cache_index],
            dt,
            candidate,
        )
        successor_value = terminal_value(
            p,
            next_states,
            strengths,
            controls_cache,
            disorder_cache,
            start_index + 1,
            dt,
            candidates,
            depth,
            worst_weight,
            residual_threshold,
            terminal_weight,
            control_stage_weight,
        )
        records.append(
            (
                current_value - successor_value,
                successor_value,
                float(np.dot(candidate, candidate)),
                float(np.linalg.norm(candidate)),
                candidate_index,
            )
        )

    margin, successor_value, norm_sq, amp, candidate_index = max(
        records,
        key=lambda item: item[0],
    )
    return {
        "phi": phi_now,
        "current_value": current_value,
        "best_fixed_successor_value": successor_value,
        "best_fixed_depth_margin": margin,
        "best_fallback_norm": norm_sq,
        "best_fallback_amp": amp,
        "best_fallback_index": candidate_index,
        "scheduled_stage_margin": max(0.0, phi_now - residual_threshold),
    }


def cache_data(
    p,
    scenarios: tuple[tuple[float, np.ndarray], ...],
    segments: int,
    horizon_steps: int,
    max_depth: int,
) -> tuple[np.ndarray, float, tuple[tuple[np.ndarray, ...], ...], tuple[tuple[np.ndarray, ...], ...]]:
    t_eval = np.linspace(0.0, p.t_final, segments + 1)
    dt = float(t_eval[1] - t_eval[0])
    cache_times = tuple(
        float(t_eval[min(j, segments)])
        for j in range(segments + horizon_steps + max_depth + 2)
    )
    controls_cache = tuple(
        tuple(interaction_frame_operator(p, hc, t) for hc in p.controls)
        for t in cache_times
    )
    disorder_cache = tuple(
        tuple(interaction_frame_operator(p, disorder, t) for _, disorder in scenarios)
        for t in cache_times
    )
    return t_eval, dt, controls_cache, disorder_cache


def audit_task_controller(
    task: str,
    controller: str,
    margin_config: MarginConfig,
    tv_config: TerminalValueHorizonConfig,
    audit_config: FixedDepthAuditConfig,
) -> list[dict[str, float | int | str]]:
    p = problem(task)
    train_strengths = (
        tv_config.train_strengths
        if controller == "terminal_value_shifted"
        else margin_config.train_strengths
    )
    train_seeds = (
        tv_config.train_seeds
        if controller == "terminal_value_shifted"
        else margin_config.train_seeds
    )
    segments = tv_config.segments if controller == "terminal_value_shifted" else margin_config.segments
    horizon_steps = (
        tv_config.horizon_steps
        if controller == "terminal_value_shifted"
        else margin_config.horizon_steps
    )
    amplitudes = (
        tv_config.amplitudes
        if controller == "terminal_value_shifted"
        else margin_config.amplitudes
    )
    worst_weight = (
        tv_config.worst_weight
        if controller == "terminal_value_shifted"
        else margin_config.worst_weight
    )
    residual_threshold = (
        tv_config.residual_threshold
        if controller == "terminal_value_shifted"
        else margin_config.residual_threshold
    )

    scenarios = tuple(
        (strength, random_disorder(seed))
        for strength in train_strengths
        for seed in train_seeds
    )
    strengths = tuple(strength for strength, _ in scenarios)
    rhos = tuple(p.initial.copy() for _ in scenarios)
    candidates = candidate_controls(amplitudes)
    beam_width = default_beam_width(task)
    max_depth = max(audit_config.value_depths)
    t_eval, dt, controls_cache, disorder_cache = cache_data(
        p,
        scenarios,
        segments,
        horizon_steps,
        max_depth,
    )

    previous_sequence: tuple[np.ndarray, ...] | None = None
    previous_phi: float | None = None
    previous_first_norm: float | None = None
    rows: list[dict[str, float | int | str]] = []

    for j, _ in enumerate(t_eval[:-1]):
        if (
            previous_sequence is not None
            and j % audit_config.audit_stride == 0
        ):
            shifted_tail = previous_sequence[1:]
            terminal_states, _ = rollout_sequence(
                rhos,
                strengths,
                controls_cache,
                disorder_cache,
                j,
                dt,
                shifted_tail,
            )
            terminal_start = min(j + len(shifted_tail), len(controls_cache) - 1)
            tail_phi = terminal_phi(p, terminal_states, worst_weight)
            print(
                f"  {task}/{controller}: fixed-depth audit step {j}/{segments} "
                f"phi={tail_phi:.6g}",
                flush=True,
            )
            for depth in audit_config.value_depths:
                record = fixed_depth_margin(
                    p,
                    terminal_states,
                    strengths,
                    controls_cache,
                    disorder_cache,
                    terminal_start,
                    dt,
                    candidates,
                    depth,
                    worst_weight,
                    residual_threshold,
                    audit_config.terminal_weight,
                    audit_config.control_stage_weight,
                )
                rows.append(
                    {
                        "task": task,
                        "controller": controller,
                        "step": j,
                        "value_depth": depth,
                        "audit_stride": audit_config.audit_stride,
                        "candidate_count": len(candidates),
                        "beam_width": beam_width,
                        "residual_threshold": residual_threshold,
                        "terminal_outside_residual": int(tail_phi > residual_threshold),
                        "tail_phi": tail_phi,
                        **record,
                    }
                )

        if controller == "terminal_value_shifted":
            sequence, _, selected_phi, _ = select_terminal_value_sequence(
                p,
                rhos,
                strengths,
                controls_cache,
                disorder_cache,
                j,
                dt,
                candidates,
                beam_width,
                tv_config,
                previous_sequence,
            )
            previous_phi = selected_phi
            previous_first_norm = float(np.dot(sequence[0], sequence[0]))
        else:
            sequence, selected_phi, first_norm, _ = select_with_margin_record(
                p,
                rhos,
                strengths,
                controls_cache,
                disorder_cache,
                j,
                dt,
                candidates,
                horizon_steps,
                beam_width,
                worst_weight,
                margin_config.energy_weight,
                previous_sequence,
                previous_phi,
                previous_first_norm,
            )
            previous_phi = selected_phi
            previous_first_norm = first_norm

        rhos = step_precomputed(
            rhos,
            strengths,
            controls_cache[j],
            disorder_cache[j],
            dt,
            sequence[0],
        )
        previous_sequence = sequence

    return rows


def summarize(rows: list[dict[str, float | int | str]]) -> list[dict[str, str]]:
    summary: list[dict[str, str]] = []
    keys = sorted(
        {
            (str(row["task"]), str(row["controller"]), int(row["value_depth"]))
            for row in rows
        }
    )
    for task, controller, depth in keys:
        group = [
            row
            for row in rows
            if str(row["task"]) == task
            and str(row["controller"]) == controller
            and int(row["value_depth"]) == depth
        ]
        margins = np.array([float(row["best_fixed_depth_margin"]) for row in group])
        scheduled = np.array([float(row["scheduled_stage_margin"]) for row in group])
        outside = np.array(
            [int(row["terminal_outside_residual"]) for row in group],
            dtype=bool,
        )
        outside_margins = margins[outside]
        outside_scheduled = scheduled[outside]
        phis = np.array([float(row["tail_phi"]) for row in group])
        summary.append(
            {
                "task": task,
                "controller": controller,
                "value_depth": str(depth),
                "audit_stride": str(int(group[0]["audit_stride"])),
                "audited_steps": str(len(group)),
                "terminal_outside_steps": str(int(np.sum(outside))),
                "fixed_positive_fraction": f"{float(np.mean(margins > 0.0)):.6g}",
                "fixed_positive_outside_fraction": (
                    f"{float(np.mean(outside_margins > 0.0)):.6g}"
                    if outside_margins.size
                    else "nan"
                ),
                "fixed_min_outside": (
                    f"{float(np.min(outside_margins)):.6g}"
                    if outside_margins.size
                    else "nan"
                ),
                "fixed_mean": f"{float(np.mean(margins)):.6g}",
                "fixed_min": f"{float(np.min(margins)):.6g}",
                "scheduled_positive_outside_fraction": (
                    f"{float(np.mean(outside_scheduled > 0.0)):.6g}"
                    if outside_scheduled.size
                    else "nan"
                ),
                "scheduled_min_outside": (
                    f"{float(np.min(outside_scheduled)):.6g}"
                    if outside_scheduled.size
                    else "nan"
                ),
                "tail_phi_mean": f"{float(np.mean(phis)):.6g}",
                "tail_phi_min": f"{float(np.min(phis)):.6g}",
            }
        )
    return summary


def write_markdown_table(f, rows: list[dict[str, str]]) -> None:
    headers = list(rows[0].keys())
    f.write("| " + " | ".join(headers) + " |\n")
    f.write("| " + " | ".join(["---"] * len(headers)) + " |\n")
    for row in rows:
        f.write("| " + " | ".join(row[h] for h in headers) + " |\n")


def write_outputs(rows: list[dict[str, float | int | str]]) -> None:
    with result_path("fixed_depth_terminal_value_margin_results.csv").open(
        "w",
        newline="",
        encoding="utf-8",
    ) as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()), lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)

    summary = summarize(rows)
    with result_path("fixed_depth_terminal_value_margin_summary.md").open(
        "w",
        encoding="utf-8",
    ) as f:
        f.write("# Fixed-Depth Terminal-Value Margin Audit\n\n")
        f.write(
            "This audit tests the stronger, unsupported fixed-depth condition "
            "`G_{j,L}(z) > G_{j+1,L}(F_k z)` on shifted-tail terminal states. "
            "The scheduled certificate used in the manuscript instead checks "
            "`G_{j,L}(z) > G_{j+1,L-1}(F_k z)`, whose Bellman margin is "
            "`[Phi(z)-tau]_+`. Negative fixed-depth rows therefore do not "
            "contradict the scheduled certificate; they show why the current "
            "score/controller should not be claimed as a fixed-depth all-time "
            "value theorem.\n\n"
        )
        write_markdown_table(f, summary)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tasks", default="Z,H")
    parser.add_argument(
        "--controllers",
        default="raw_shifted,terminal_value_shifted",
        help="Comma-separated subset of raw_shifted, terminal_value_shifted.",
    )
    parser.add_argument("--stride", type=int, default=10)
    parser.add_argument("--depths", default="1")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    audit_config = FixedDepthAuditConfig(
        value_depths=tuple(int(item) for item in args.depths.split(",") if item.strip()),
        audit_stride=args.stride,
    )
    margin_config = MarginConfig()
    tv_config = TerminalValueHorizonConfig()
    rows: list[dict[str, float | int | str]] = []
    controllers = [item.strip() for item in args.controllers.split(",") if item.strip()]
    for controller in controllers:
        if controller not in {"raw_shifted", "terminal_value_shifted"}:
            raise ValueError(f"unknown controller {controller!r}")
    for task in [item.strip() for item in args.tasks.split(",") if item.strip()]:
        for controller in controllers:
            print(f"auditing fixed-depth margins for {task}/{controller}", flush=True)
            rows.extend(
                audit_task_controller(
                    task,
                    controller,
                    margin_config,
                    tv_config,
                    audit_config,
                )
            )
    write_outputs(rows)
    for row in summarize(rows):
        print(row)


if __name__ == "__main__":
    main()
