"""Sweep terminal-fallback alphabets for the shifted-fallback certificate.

This audit keeps the realized shifted-fallback trajectory generated by the
default beam-horizon controller, then recomputes the terminal-fallback margin
with several denser fallback alphabets that stay within the same amplitude cap.
It is a certificate-design audit: a better margin fraction indicates that the
fallback alphabet is a promising way to make Proposition terminal-fallback
active more often, but it does not by itself replace the main held-out
controller row.
"""

from __future__ import annotations

import csv
from dataclasses import dataclass

import numpy as np

from horizon_lyapunov import (
    candidate_controls,
    default_beam_width,
    interaction_frame_operator,
    problem,
    random_disorder,
    step_precomputed,
)
from paths import result_path
from shifted_fallback_margin_audit import (
    MarginConfig,
    score_sequence,
    select_with_margin_record,
)


@dataclass(frozen=True)
class FallbackSpec:
    name: str
    amplitudes: tuple[float, ...]


FALLBACK_SPECS = (
    FallbackSpec("default", (0.5, 1.0, 2.0, 3.0, 4.0)),
    FallbackSpec("midpoint_inrange", (0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0)),
    FallbackSpec(
        "dense_inrange",
        (0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.5, 3.0, 3.5, 4.0),
    ),
)


def best_margin_for_alphabet(
    p,
    rhos: tuple[np.ndarray, ...],
    strengths: tuple[float, ...],
    controls_cache: tuple[tuple[np.ndarray, ...], ...],
    disorder_cache: tuple[tuple[np.ndarray, ...], ...],
    start_index: int,
    dt: float,
    previous_sequence: tuple[np.ndarray, ...],
    previous_phi: float,
    previous_first_norm: float,
    fallback_candidates: tuple[np.ndarray, ...],
    horizon_steps: int,
    worst_weight: float,
    energy_weight: float,
) -> tuple[float, float, float, int]:
    shifted_tail = previous_sequence[1:]
    best_margin = -np.inf
    best_phi = np.nan
    best_norm = np.nan
    for fallback in fallback_candidates:
        shifted_sequence = shifted_tail + (fallback,)
        _, _, phi, _ = score_sequence(
            p,
            rhos,
            strengths,
            controls_cache,
            disorder_cache,
            start_index,
            dt,
            shifted_sequence,
            worst_weight,
            energy_weight,
        )
        fallback_norm = float(np.dot(fallback, fallback))
        margin = previous_phi - phi - energy_weight * (
            fallback_norm - previous_first_norm
        )
        if margin > best_margin:
            best_margin = margin
            best_phi = phi
            best_norm = fallback_norm
    return best_margin, best_phi, best_norm, len(fallback_candidates)


def audit_task(task: str, config: MarginConfig) -> list[dict[str, float | int | str]]:
    p = problem(task)
    t_eval = np.linspace(0.0, p.t_final, config.segments + 1)
    dt = float(t_eval[1] - t_eval[0])
    scenarios = tuple(
        (strength, random_disorder(seed))
        for strength in config.train_strengths
        for seed in config.train_seeds
    )
    strengths = tuple(strength for strength, _ in scenarios)
    rhos = tuple(p.initial.copy() for _ in scenarios)
    design_candidates = candidate_controls(config.amplitudes)
    fallback_candidates = {
        spec.name: candidate_controls(spec.amplitudes) for spec in FALLBACK_SPECS
    }
    cache_times = tuple(
        float(t_eval[min(j, config.segments)])
        for j in range(config.segments + config.horizon_steps)
    )
    controls_cache = tuple(
        tuple(interaction_frame_operator(p, hc, t) for hc in p.controls)
        for t in cache_times
    )
    disorder_cache = tuple(
        tuple(interaction_frame_operator(p, disorder, t) for _, disorder in scenarios)
        for t in cache_times
    )

    previous_sequence: tuple[np.ndarray, ...] | None = None
    previous_phi: float | None = None
    previous_first_norm: float | None = None
    beam_width = default_beam_width(task)
    rows: list[dict[str, float | int | str]] = []

    for j, _ in enumerate(t_eval[:-1]):
        if (
            previous_sequence is not None
            and previous_phi is not None
            and previous_first_norm is not None
        ):
            for spec in FALLBACK_SPECS:
                margin, phi, fallback_norm, candidate_count = best_margin_for_alphabet(
                    p,
                    rhos,
                    strengths,
                    controls_cache,
                    disorder_cache,
                    j,
                    dt,
                    previous_sequence,
                    previous_phi,
                    previous_first_norm,
                    fallback_candidates[spec.name],
                    config.horizon_steps,
                    config.worst_weight,
                    config.energy_weight,
                )
                rows.append(
                    {
                        "task": task,
                        "step": j,
                        "fallback_spec": spec.name,
                        "candidate_count": candidate_count,
                        "previous_terminal_phi": previous_phi,
                        "best_margin": margin,
                        "best_fallback_phi": phi,
                        "best_fallback_norm": fallback_norm,
                        "terminal_outside_residual": int(
                            previous_phi > config.residual_threshold
                        ),
                        "residual_threshold": config.residual_threshold,
                    }
                )

        sequence, phi, first_norm, _ = select_with_margin_record(
            p,
            rhos,
            strengths,
            controls_cache,
            disorder_cache,
            j,
            dt,
            design_candidates,
            config.horizon_steps,
            beam_width,
            config.worst_weight,
            config.energy_weight,
            previous_sequence,
            previous_phi,
            previous_first_norm,
        )
        control = sequence[0]
        rhos = step_precomputed(
            rhos,
            strengths,
            controls_cache[j],
            disorder_cache[j],
            dt,
            control,
        )
        previous_sequence = sequence
        previous_phi = phi
        previous_first_norm = first_norm

    return rows


def summarize(rows: list[dict[str, float | int | str]]) -> list[dict[str, str]]:
    summary = []
    keys = sorted({(str(row["task"]), str(row["fallback_spec"])) for row in rows})
    for task, spec in keys:
        spec_rows = [
            row
            for row in rows
            if str(row["task"]) == task and str(row["fallback_spec"]) == spec
        ]
        margins = np.array([float(row["best_margin"]) for row in spec_rows])
        outside = np.array(
            [int(row["terminal_outside_residual"]) for row in spec_rows],
            dtype=bool,
        )
        outside_margins = margins[outside]
        summary.append(
            {
                "task": task,
                "fallback_spec": spec,
                "candidate_count": str(int(spec_rows[0]["candidate_count"])),
                "audited_steps": str(len(spec_rows)),
                "positive_margin_fraction": f"{float(np.mean(margins > 0.0)):.6g}",
                "terminal_outside_steps": str(int(np.sum(outside))),
                "positive_terminal_outside_fraction": (
                    f"{float(np.mean(outside_margins > 0.0)):.6g}"
                    if outside_margins.size
                    else "nan"
                ),
                "margin_mean": f"{float(np.mean(margins)):.6g}",
                "margin_median": f"{float(np.median(margins)):.6g}",
                "margin_min": f"{float(np.min(margins)):.6g}",
                "margin_p10": f"{float(np.quantile(margins, 0.1)):.6g}",
                "margin_max": f"{float(np.max(margins)):.6g}",
            }
        )
    return summary


def write_outputs(rows: list[dict[str, float | int | str]]) -> None:
    with result_path("terminal_fallback_alphabet_sweep_results.csv").open(
        "w",
        newline="",
        encoding="utf-8",
    ) as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

    summary = summarize(rows)
    headers = list(summary[0].keys())
    with result_path("terminal_fallback_alphabet_sweep_summary.md").open(
        "w",
        encoding="utf-8",
    ) as f:
        f.write("# Terminal-Fallback Alphabet Sweep Summary\n\n")
        f.write(
            "The realized shifted-fallback trajectory is kept fixed while the "
            "terminal fallback alphabet is varied within the same amplitude cap. "
            "This is a certificate-design audit, not a replacement held-out "
            "controller result.\n\n"
        )
        f.write("| " + " | ".join(headers) + " |\n")
        f.write("| " + " | ".join(["---"] * len(headers)) + " |\n")
        for row in summary:
            f.write("| " + " | ".join(row[h] for h in headers) + " |\n")


def main() -> None:
    config = MarginConfig()
    rows = []
    for task in ("Z", "H"):
        print(f"sweeping terminal fallback alphabets for {task}", flush=True)
        rows.extend(audit_task(task, config))
    write_outputs(rows)
    for row in summarize(rows):
        print(row)


if __name__ == "__main__":
    main()
